### PR TITLE
Amend latest tags

### PR DESCRIPTION
**Pull request by ShihabMehboob**
Amended latest tags to a version number.

### CODE REVIEW

**Comment by mhamwala** [comment]
Not sure if we want to pull these in as we don't know if they are stable/unstable, thought it was experimental to see if the very latest images would work?

**Comment by ShihabMehboob** [comment]
@mhamwala I think the main reason for this, according to https://github.ibm.com/runtimes/cloud-functions-icp/issues/24, is so that we don't always use the latest version so that it doesn't break something with an update. If we're using a fixed version that we know works, it's more stable.

**Comment by mhamwala** [comment]
Need to figure out how to find/test a fixed/stable version. Current tags seem to be latest of the 'latest' or the same as 'latest'.

**Comment by tomleah** [comment]
Closing due to being added in community. https://github.com/apache/incubator-openwhisk-deploy-kube/pull/362

**Pull request closed without merging**
